CREATE TABLE `pagination`.`articulos` }( `ID` INT NOT NULL AUTO_INCREMENT 
, `ARTICLE` VARCHAR(1000000) NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;

INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('1', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('2', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('3', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('4', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('5', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('6', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('7', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('8', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('9', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('10', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('11', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('12', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('13', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('14', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('15', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('16', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
INSERT INTO `articulos` (`ID`, `ARTICLE`) VALUES ('17', 'kdnklqjwndfckljqwnfljkqwnfljkqw qldfnlkqwefnmlkqwfn lmjqwe flkojqwfn lkqwf nlkqwf ljkmqwfn lkqwfnlkqwfnlkqw flmkqw flkjmqw nflkqw flkqwnflkqwnflkqw flkq wflpkqwnflkqwnflk');
